import { EmbeddingService } from '../../adapters/openai/embedding';
import { getPineconeIndexClient } from '../../adapters/pinecone/operations';
import type { Document } from './document-loader';
import logger from '../firebase/logger';

export interface UpsertOptions {
  batchSize?: number;
  dryRun?: boolean;
}

export interface UpsertMetrics {
  documentsProcessed: number;
  vectorsUpserted: number;
  failedCount: number;
  totalTime: number;
}

interface UpsertVector {
  id: string;
  values: number[];
  metadata: Record<string, any>;
}

const DEFAULT_OPTIONS: Required<UpsertOptions> = {
  batchSize: 100,
  dryRun: false,
};

const embeddingService = new EmbeddingService();

/**
 * Embed documents using OpenAI
 */
async function embedDocuments(documents: Document[]): Promise<UpsertVector[]> {
  const vectors: UpsertVector[] = [];
  logger.info(`Embedding ${documents.length} documents`);

  for (const doc of documents) {
    try {
      const embedding = await embeddingService.createEmbedding(doc.text);

      vectors.push({
        id: doc.id,
        values: embedding,
        metadata: {
          text: doc.text.substring(0, 1000),
          ...doc.metadata,
        },
      });
    } catch (error) {
      logger.warn(
        `Failed to embed document ${doc.id}: ${(error as any)?.message || error}`,
      );
    }
  }

  logger.info(
    `Successfully embedded ${vectors.length}/${documents.length} documents`,
  );
  return vectors;
}

/**
 * Upsert vectors to Pinecone in batches
 */
async function upsertVectors(
  vectors: UpsertVector[],
  batchSize: number,
): Promise<number> {
  const index = getPineconeIndexClient();
  let upsertedCount = 0;

  logger.info(`Upserting ${vectors.length} vectors in batches of ${batchSize}`);
  for (let i = 0; i < vectors.length; i += batchSize) {
    /**
     * Upsert multiple vectors as a batch
     * Sample batch data structure generated by vectors.slice() (assuming vectors: Array<{id:string, values:number[], metadata?:...}>):
     * [
     *   {
     *     id: "vec1",
     *     values: [0.01, 0.02, ..., 0.1536], // embedding float array
     *     metadata: { text: "Sample text 1" }
     *   },
     *   {
     *     id: "vec2",
     *     values: [0.1, 0.2, ..., 0.1456],
     *     metadata: { text: "Sample text 2" }
     *   },
     *   // ... up to slice length (e.g. 100 vectors max)
     * ]
     */
    const batch = vectors.slice(i, i + batchSize);

    try {
      await index.upsert({records: batch});
      upsertedCount += batch.length;
      logger.info(`Upserted batch ${Math.floor(i / batchSize) + 1}`);
    } catch (error) {
      logger.error(
        `Failed to upsert batch ${Math.floor(i / batchSize) + 1}: ${(error as any)?.message || error}`,
      );
    }
  }

  return upsertedCount;
}

/**
 * Main upsert pipeline: documents → embeddings → vectors → pinecone
 */
export async function upsertDocuments(
  documents: Document[],
  options: UpsertOptions = {},
): Promise<UpsertMetrics> {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const startTime = Date.now();

  logger.info('Starting upsert pipeline', {
    documentCount: documents.length,
    batchSize: opts.batchSize,
    dryRun: opts.dryRun,
  });

  if (documents.length === 0) {
    throw new Error('No documents provided');
  }

  // Step 1: Create embeddings
  const vectors = await embedDocuments(documents);
  if (vectors.length === 0) {
    throw new Error('No vectors created');
  }

  // Step 2: Upsert to Pinecone (skip if dry run)
  const vectorsUpserted = opts.dryRun
    ? vectors.length
    : await upsertVectors(vectors, opts.batchSize);

  const totalTime = Date.now() - startTime;
  const failedCount = documents.length - vectors.length;

  logger.info('Upsert pipeline completed', {
    documentsProcessed: documents.length,
    vectorsUpserted,
    failedCount,
    totalTime,
  });
  return {
    documentsProcessed: documents.length,
    vectorsUpserted,
    failedCount,
    totalTime,
  };
}
